### ISSUE TITLE
国内linux开源人物大起底

### ISSUE THREAD

**Issue by lkml-likexu** [lkml-likexu/kde#113]

**Comment by liker12134** [comment]
* 2014.10.19 北京

    * Mauri Whalen@Intel@Linux Kernel, Intel and China	
      * Vice President and Director at Intel Corporation
      * https://www.linkedin.com/in/mauri-whalen-2ba0221/
    * 武内、 缪勰@Fujitsu@ Btrfs: Current status and future prospect	
    * 杨伟@IBM@SRIOV & Power
      * IBM的Linux技术专家杨伟，他对SR-IOV技术及Power架构技术进行了讲解。他介绍称，作为一种基于硬件的虚拟化解决方案,SR-IOV技术可提高性能和可伸缩性。
    * 林晓峰@新浪@Fastsocket: A Scalable Kernel TCP Socket
      * 北京邮电大学硕士研究生毕业，原新浪基础架构部高级系统开发工程，高性能 Linux 网络协议栈实现 Fastsocket 作者。 2014 年底加入知乎，现任技术平台团队的负责人。
    * Mark Gross@Intel@Lessons learn while maintaining Android kernels at Intel	
      * https://www.linkedin.com/in/mark97229/
    * 汤晨@Fujitsu@ Linux内核和QEmu中的内存热插拔	
      * 汤晨在《Introduction to ACPI Based Memory Hotplug》的技术演讲中介绍了FNST的DP（Dynamic Partition）团队为实现内存热插拔所做出的贡献。内存热插拔是动态调配系统资源的重要基础，但在内核内存迁移的问题上，还没有完美的解决方案。
    * 朱辉@小米@Buddy系统中 CMA 的实现和对其问题的改进	
      * 小米电视 高级开发工程师
      * 此技术首次搭载在小米盒子1GB增强版上，让系统运行更顺畅
    * Li Zhang@IBM@ KVM on Power
      * http://researcher.watson.ibm.com/researcher/view.php?person=us-zhangli
      * Dr. Li Zhang is the manager of the System Analysis and Optimization group at IBM T.J. Watson Research Center.
    * 刘奖@Intel@Reconstruct x86 Interrupt Architecture with Hierarchy IRQ Domain
      * 刘奖——2004年至2010年就职于英特尔开源中心，2011年加入华为，现任华为中央软件院欧拉实室架设部长。
      * 依托Linux Foundation在华为内部大力推广开源文化，两年内培养了一支三十多人的团队参与Linux社区开发，在Linux内核多个技术领域作出重要贡献，最新3.10内核贡献排名进入前20，发起ktap开源项目并获得大量关注。
    * 董昊@阿里巴巴@一个支持资源隔离的高效 IO 调度器	
      * 花名 三百 阿里巴巴雅虎中国、淘宝组
      * https://www.slideshare.net/donghao/flashcache-65494979
    * 龚磊@华为@如何实现NFV场景虚拟机隔离部署
      * 龚磊，2011年毕业后入职华为。自2013年开始投入QEMU社区（虚拟化开源社区），近2年的厚积薄发，个人贡献130+patch，支撑我司排名迅速上升，获得社区高度认可，并在2014年11月成为QEMU社区Maintainer，是目前虚拟化第一个Maintainer。

  * 2015.10.17-18 南京 南京大学

    * Fujitsu@Kamezawa Hiroyuki@容器和富士通
      * https://www.linkedin.com/in/hiroyuki-kamezawa-54020652/
      * 毕业于东京大学
    * Intel@Eddie Dong@Virtualization及KVM的现状，发展以及未来
      * https://www.linkedin.com/in/dong-eddie-47927a2b/
      * 中国上海 毕业于上海交大
    * IBM@何佳@OpenPOWER中的内核新功能
      * 很神秘的样子	
    * 微软@Dr. K. Y. Srinivasan@Hyper-v: 运行Linux工作负载的卓越平台
      * 合伙人级别架构师和软件工程经理
    * 华为@谢祥有@如何提升内核实时性
      * 华为虚拟化资深工程师，致力于KVM平台开发。
    * 富士通@瞿文若@如何参与到内核文件系统开发
      * 富士通内核开发者，RHCE CCNP认证持有者,主要参与Btrfs开发。 Btrfs内核主要贡献为 Async-thread代码更新，Btrfs quota代码重构，用户层主要工具的强化，以及内核用户层的bugfix。
    * 华为@龚磊@一种新的加解密Virtio驱动框架
    * 清华大学@陈渝 、茅俊杰@无语义假设的引用计数分析
      * 陈渝 清华大学 副教授  操作系统 **Linux标准化**工作组
      * 茅俊杰 清华计算机系博士生 研究方向是操作系统分析与优化
    * 中兴@谢宝友@Linux内存屏障
      * 中兴通讯操作系统团队技术总工
    * Linaro CEO@乔治 格雷@如何打造一个便宜的全功能Linux Kernel开发平台
      * https://www.linkedin.com/in/georgegrey/
      * 毕业于英国剑桥大学
    * IBM@冯博群@RCU临界区中数据访问的跟踪
      * IBM LTC内核工程师
    * WindRiver@薛英@TIPC(Transparent Inter-Process Communication protocol)协议的过去现在以及未来
      * 从事Linux系统开发超过10年以上。从事风河Linux系统维护的工作，主要负责解决Linux内核出现的各样的bug.同时作者目前还是TIPC协议栈Linux kernel社区的Maintainer。另外日常还负责维护TIPC社区邮件列表，回答和解决TIPC用户的各种各样的问题。
    * 阿里@朱延海@为分布式块存储系统使用Bcache做本地缓存
      * 阿里云内核组工程师
    * Intel@陆宝辂@通过USB 3调试端口调试Linux内核
      * 陆宝辂，工科硕士，毕业于清华大学。2005年加入Intel并一直从事UNIX/Linux内核的开发和优化。他主要开发了Solaris下的Intel vt-d驱动；USB 3主机控制器驱动。他参与开发了Solaris IOH热插拔支持。他是xHCI规格书的贡献者之一，同时积极参与Linux USB社区的开发和讨论。目前，他专注于USB 3调试端口和USB 3.1的开发。
    * Linaro@时奎亮@深入Linux内核调度器
      * Alex Shi 毕业于华中师范大学物理系。现在在Linaro公司负责维护Linaro 稳定版内核版本。
      * 加入Linaro之前，在英特尔开源技术中心工作，主要负责Linux内核在x86平台上的性能和功耗测试优化工作。
    * 富士通@李智坚@COLO: 基于粗粒度同步的虚拟机热备方案
      * 富士通南大Linux工程师, 目前主要致力于KVM虚拟机热备项目(COLO on KVM)
    * 华为@李泽帆@Stable Kernel的社区运作机制
    * Intel@陈渝@轻量级休眠
      * 就职于Intel 开源技术中心，ACPI组。主要关注电源管理相关领域，例如Suspend-to-RAM，Suspend-to-Idle，休眠，温度管理，cpufreq/cpuidle驱动。平时的工作主要侧重ACPI的故障解决，电源管理里的内核故障以及suspend/resume的耗时优化，同时也会关注一些suspend/resume过程中的设备驱动问题。
    * 亚马逊@于鹏@内核调试工具 - systemtap
      * 2005年毕业于北京理工大学，毕业后的前七年从事嵌入式驱动开发行业，写过若干linux设备驱动程序。后来就职于红帽软件售后部门，负责解决linux内核bug以及进行系统性能调优。现就职于亚马逊AWS售后部门。喜欢学习计算操作系统，编译原理，算法等底层技术，开源软件爱好者，热衷于使用开源软件，擅长libreoffice/gimp等开源工具。

  * 2016.10.22-23 上海 复旦大学邯郸校区

    * 李光成@IBM@利用和扩展 Linux内核功能管理大规模生产环境中的 Linux容器资源
      * IBM中国研究院资深研究员，研究方向是云计算基础设施
    * 魏建刚@富士通@次世代测试框架 Avocado 在虚拟化测试中的应用
      * https://www.linkedin.com/in/%E5%BB%BA%E5%88%9A-%E9%AD%8F-a9718aa1/
      * 硕士毕业于江南大学
    * 宋宝华、 刘勃、徐西宁@LEP开源项目小组@Linux Performance Profiling and Visualization
      * LEP(LINUX EASY PROFILING) 是Linuxer之LEP项目组（Barry Song，Mac Xu，陈松等以及陈莉君老师）正在致力于打造的一个开源项目，LEP的全称是Linux Easy Profiling（Linux易用剖析器），核心特点在于Easy（简单），主要功能在乎Profiling（剖析）。LEP的网址是http://www.linuxep.com 
    * 汪黎@国防科技大学@Design and Implementation of Distributed Transaction for Ceph Distributed Storage	
      * 优秀博士学位论文奖获奖者
      * 提出了多项式时间的最优或近似最优的流寄存器文件分配算法，相对目前国际流行的算法，有明显的分配性能改进
    * Ying Huang@Intel@Optimizing the Linux Kernel Swap Subsystem
      * https://www.linkedin.com/in/huang-ying-a840488/
      * 毕业于浙江大学	
    * Alex Shi@LINARO@Efficient Kernel Backporting	
    * 杨伟@Huawei@虚拟化平台多核扩展性的研究	
      * 同名同姓过多难确认
    * Chao Ye@Redhat@CRIU Introduction
      * https://www.linkedin.com/in/derekye/
      * 毕业于中科大	
    * 赵祯龙@浪潮@KVM on ARM	
      * https://www.linkedin.com/in/%E7%A5%AF%E9%BE%99-%E8%B5%B5-437600b1/
      * 虚拟化项目组TeamLeader 毕业于北航
    * Gavin Guo/陳亮@Canonical@KASAN 在 OpenStack 云计算平台上的调试经验	
      * Taiwan Linux Kernel Hackers Public Group
      * Canonical Gavin Guo
        * Canonical Linux 社區內核開發者，專長解決Ubuntu OpenStack雲計算平台內核相關疑難雜症，特別針對內存架構NUMA(non-uniform memory access)、SLUB分配器，與KASAN(Kernel Address Sanitizer)都有著通盤透徹的理解與無數的實作經驗 。在此之前任職於台灣自有處理器架構Andes公司內核開發團隊，負責內核處理器架構層的維護與實作。更早期曾任職BIOS與Linux驅動開發。在豐富的系統開發經驗累積之下，在內核、編譯器工具鏈，與處理器架構系統級別的協同開發與調試中扮演不可或缺的重要角色。
      * 陳亮
        * Canonical OpenStack兼內核開發者，早期OpenStack Grizzly即加入的活躍社區開發者，曾在IBM OpenStack upstream團隊。在過去幾年內在OpenStack貢獻了可觀的代碼量，特別是在Heat, Cinder, Keystone元件。近來集中在Nova以及libvirt/qemu/kvm virtualization技術。過去曾任職於TripAdvisor，是Java開發者，熟捻前端/後端技術。早年在校主修OS方向，而後保持著對OS的關注研究。由於全方面的知識面工作經驗，鑄造了陳亮這位少見的generalist，目前在Canonical負責OpenStack跨多組件全棧內核系統級別的問題分析。
    * Dr. K. Y.Srinivasan@Microsoft@Linux on Hyper-V - A Status Report	
      * 合伙人级别架构师和软件工程经理
    * Jike Song@Intel@VFIO-based Mediated Pass Through - KVMGT as an Example
      * https://www.linkedin.com/in/albcamus/
      * x86/PCIe/kernel, especially wrt. virtualization and system development.
      * 毕业于哈工大
    * 吴章金@魅族@The Principle and Practice of Ftrace	
      * 魅族科技研发中心高级经理
    * 宋卓(文侑)@Ali@阿里内核高性能统计模块的实践	
      * 难确认相关信息
    * 石东佳@IBM@System z 上的 Channel I/O Pass-Through	
      * 难确认相关信息
    * Gonglei(Arei)	@Huawei@Introduction of New Virtio Crypto Device	

  * 2017 清华大学

    * Tony Luck@Intel@How to deal with noisy neighbors?	
      * https://www.linkedin.com/in/tony-luck-5439735/
      * 毕业于牛津大学数学系 美国 旧金山
    * 杨瑞@IBM@IBM LinuxOne and virtualization technology advancement
      * 难确认相关信息	
    * 马士淼@富士通@ Standardization for Container	
      * OCI Maintainer. *富士通*南大软件技术有限公司软件工程师，目前是OCI runtime-tools 的maintainer
    * 陶文苇@Alibaba@阿里内部集群的内存超卖
      * 阿里巴巴系统软件事业部Linux内核工程师，2012年毕业于哈尔滨工业大学(威海)
      * 应该曾在三星工作	
    * Dennis Chen@ARM@GIC based interrupt handling mechanism on ARM64
      * https://github.com/arm64b
      * Work for ARM company. Focusing on ARM64 enterprise software ecosystem, such as Linux kernel, virtualization, container, firmware, etc.	
    * 刘振君@南开大学@嵌入式Linux系统IPv6-in-IPv4丢包问题浅析
      * 南开大学硕士在读	
    * Neil Sun@Qingcloud@如何编写Qemu后端块设备驱动	
      * 内核工程师 Neil Sun 孙锋
      * 在加入青云QingCloud之前，曾是三星通信研究院的内核研发工程师，负责对三星 Android 移动端设备 Linux 内核稳定性的维护。在加入青云之后，除日常维护青云QingCloud 云平台 Linux 内核，保证云物理机的稳定运行，还会对诸如虚拟化、分布式存储、SDS 等进行研发支撑。
    * 冯博群@Intel@Wait/wake in Linux kernel and waketorture	
    * 李万鹏@社区@Low-latency KVM Hypervisor	
      * https://www.linkedin.com/in/wanpeng-li-50794375/
      * 曾就职于intel IBM 金山
    * 赵以民@IBM@System z PCIe architecture virtualization implementation on Linux using KVM and QEMU	
      * https://www.linkedin.com/in/%E4%BB%A5%E6%B0%91-%E8%B5%B5-544660121/
    * 杨亚军@Tencent@一种新的操作系统入侵检测框架
      * 腾讯操作系统和底层虚拟化平台研发工作负责人	
    * Han Han@Red Hat@OSS-Fuzz-容器和云计算在模糊测试中的应用
      * 未确认
    * Ming Lei@Red Hat@BLOCK Multi-Queue(MQ) IO scheduler	
      * https://www.linkedin.com/in/tomlei/
      * Red Hat  Xidian University
    * Figo Zhang, Hao Wu@Intel@Intel FPGA Linux Driver solution and Upstreaming Status	
      * Figo zhang is a software engineer at Intel DCG (Data Center Group). Currently He focused on FPGA Linux driver development for Intel Xeon+FPGA project. 
      * Hao Wu is a senior software engineer at Intel Open Source Technology Center, where he is responsible for the design and development of the Linux kernel device drivers for Intel FPGA devices. Prior to working on FPGA, he worked on kernel driver development for Intel mobile platforms for several years.
    * 李秀波, 刘源@中国移动@Linux LIO 与 TCMU 用户空间透传
      * 李秀波，Linux Kernel Freescale Sound soc的Maintainer，现就职于中国移动（苏州）研发中心，致力于苏研虚拟化产品基础软件的支持与开发、Linux Kernel 开发与调优、协同 Readhat/IBM 对 LIO/TCMU 和Open-iscsi tcmu-runner 进行开发与维护等，目前已经向 Linux Kernel 及 KVM 社区贡献补丁约200个， uboot 社区近10个，open iscsi 社区近60个。
      * 刘源，中国移动苏州研发中心 高级架构师兼基存储产品组负责人。热爱开源，是分布式存储Sheepdog维护者和主要贡献者之一，也是多个开源项目（包括LIO TCMU)代码贡献者。目前负责苏研虚拟化，存储，内核，NFV等底层系统开发。曾就职于英特尔上海开源技术中心(kvm/xen)，阿里云（vhost-blk/Sheepdog/盘古），青云（SDS），从事内核，虚拟化，存储系统等底层软件研发。
    * 刘铮@阿里云@LINUX 内存存储栈上面临的问题与挑战
      * 刘铮，阿里云高级技术专家。2011年加入淘宝内核组参与内核开发工作至今。目前主要负责阿里巴巴集团内核存储方面的研发工作，EXT4文件系统社区主要研发人员。
      * 齐江，阿里云操作系统研发专家，毕业于东南大学，主要负责Linux内核文件系统和块层等存储领域的研发工作。在Linux内核主干有超过80个commit，主要贡献在OCFS2集群文件系统，并协助维护OCFS2。当前工作主要为Linux内核IO资源隔离在多种业务场景下的应用。
    * 李枫@Citrix@eBPF In-kernel Virtual Machine & Cloud computing
      * 李枫，熟悉基于ARM+Linux的嵌入式软件平台架构，在甲骨文JavaME、高通BREW、摩托罗拉P2K、谷歌Android、三星Tizen等移动平台上有十余年研发经验，包括一年多Linux内核开发经历。近几年主要从事云计算相关研发工作。
        2017至今，于Citrix（南京）担任Staff Software Engineer，从事云基础设施相关研发工作；2015至2017年于EMC（上海）担任Principal Software Engineer从事云存储相关研发工作；2014至2015于阿里巴巴（杭州）担任 Wireless Technology Expert，从事移动安全开发工作。此外，李枫是《灰帽黑客 第4版：正义黑客的道德规范、渗透测试、攻击方法和漏洞分析技术 》一书中文版的主要译者（http://product.dangdang.com/23927890.html）。
    * 金垚@Intel@使用Linux perf分析应用程序性能 - 以一个示例介绍Intel performance counter, PEBS, timed LBR,Intel PT的使用	
      * 金垚，在Intel OTC从事开源工作近9年，具有丰富的Solairs及 Linux内核开发经验，擅长于performance counter领域。
    * 郝庆丰@IBM@高效垃圾回收—存储保护特性	
      * 郝庆丰，IBM中国Base KVM开发组长，具有12年Linux和Unix下服务器系统开发和2年KVM和Linux内核开发经验，已在社区提交关于新功能的4个内核代码包和5个QEMU代码修正包，并报告一个QEMU bug。作者积极参与各类社区活动，并在2010年出版书籍《返璞归真--Unix技术内幕》，该书讲解Unix Edition 6内核的具体实现，深入浅出，鞭辟入里，受到读者好评和来信。作者获得国家软件水平考试《系统分析师》和《软件设计师》证书。

* 更多大佬

  * 冯晓焰、魏永军、傅文庆、陈绪、康烁、Coly Li、陈斌、张桦、唐新亭

**Comment by liker12134** [comment]
#### 2017中国开源年会 China Open Source Conference 2017
* 人
  * 陈欧侃 
  * Roert Lu
  * 老衲
  * 红旗樊总
  * 用友白总
  * 开源社理事Ted
  * 梁莉
  * 史璞金、司延腾
  * 金钢
* 组织
  * Linux人社区
  * 黄嘴企鹅论坛（LinuxSir）
  * 中国Linux公社（linuxfans.org）
  * Linux伊甸园（LinuxEden）
  * 用友
  * 巨杉数据库
  * 开源社
  * KDE China
  * 红旗Linux
    * 红旗教育学院
    * 红旗软件的产品论坛
* 内容
  * Linux桌面
* 工具
  * Linux下的专业翻译工具——Lokalize
* 想法
  * 以Linux人才培养为主
  * 一个连通国内各开源社区、企业的开源资讯中心
  * 酷猫开发计划
  * 校园联络大使
* 思路
  * 一个管理者必须具备宽广的胸怀和娱乐的精神
  * 找到一条可持续推进XX计划的路线
  * 社区成员的认领方式

**Comment by xuliker** [comment]
http://kernel.taobao.org/index.php?title=%E9%A6%96%E9%A1%B5

**Comment by taoxu916** [comment]
I find you :) interesting

**Comment by navigaid** [comment]
mark

**Comment by smcdef** [comment]
标题改成＂CLK编年史＂可能更合适

**Comment by jw915086731** [comment]
2022 clk已出炉
